### ISSUE TITLE
Environmental variables of DLR libraries

### ISSUE THREAD

**Issue by nanlovescan** [jasonkaye/libdlr#3]
Hi,

This is Nan, a user of DLR libraries on Mac system. I have an Anaconda 4.11.0 with intel mkl, blas, lapack installed. 
I found some issues which may be related to the environmental variables of DLR libraries.
1. Fortran code: libdlr will always look for other libaries such as intel mkl etc in the root path /usr/local/lib. However, in my case all of these libraries are in the conda directory. I fixed this by manually copying the related libraries to /usr/local/lib. Furthermore, I have to use absolute directory when compiling the code, for example as gfortran sc_mf.f90 /usr/local/lib/libdlr.dylib -o sc_mf. Is it possible to set up environmental variables for DLR library and for finding all of the other libraries automatically?
2. It looks like pydlr is incompatible with my python3 from Anaconda and I cannot import it. I guess this may also be related to environmental variables.

Thanks,
Nan

**Comment by HugoStrand** [comment]
Dear Nan,

Thank you for reaching out.

Could you please provide some error output from `cmake` when trying to detect BLAS/LAPACK?

Are you using `cmake` also installed with Conda? (You can check which one you are using by running `which cmake`)

If you are not using `cmake` installed from Conda, please consider trying to install also `cmake` with conda and try using that version to automatically detect the BLAS/LAPACK libraries you have installed in your conda environment.

In the case of the python module `pydlr` have you tried to simply install it using the `pip3` command, i.e.
```
pip3 install --user pydlr
```
and then testing to import it with ``python3 -c "import pydlr"``?

If this is not working could you please give some example of the error messages produced?

Cheers, Hugo

**Comment by nanlovescan** [comment]
Hi Hugo,

Thanks for your response.
Yes, cmake is also installed with Conda. 

The installation process has no problem and everything went well.
The problem appears when I used libdlr to compile and run a simple example such as sc_mf.f90.

Error message (using mkl lib as an example):
dyld[17236]: Library not loaded: @rpath/libmkl_intel_lp64.1.dylib
  Referenced from: /usr/local/lib/libdlr.dylib
  Reason: tried: '/usr/local/lib/libmkl_intel_lp64.1.dylib' (no such file), '/usr/lib/libmkl_intel_lp64.1.dylib' (no such file)
Abort trap: 6

I just tried the pip install and it works now. Thanks for the help!

Nan

**Comment by HugoStrand** [comment]
Dear Nan,

Ok! I see. This is just a problem with your environment variables at runtime. If cou look closely at the output when you run `cmake` you will find something similar to

```
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /opt/local/lib/libopenblas.dylib  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /opt/local/lib/libopenblas.dylib;-lm;-ldl  
```

The path `/opt/local/lib` should of course be different on your system.

Please try to run your compiled example with the prepended environment variable

```
DYLD_LIBRARY_PATH=/opt/local/lib/:$DYLD_LIBRARY_PATH ./sc_mf
```

where you replace `/opt/local/lib/` with whatever path `cmake` prints on your system.

Good luck!

Best, Hugo

**Comment by nanlovescan** [comment]
Got it, thanks!
