### ISSUE TITLE
Small lambda seg fault in pydlr 

### ISSUE THREAD

**Issue by harrisonlabollita** [jasonkaye/libdlr#5]
For small values of $\Lambda$, the DLR discretization fails and seems to result in a segmentation fault. This behavior seems to be associated with the setting of the parameter ``nmax`` [here](https://github.com/jasonkaye/libdlr/blob/7eeb1aea0e990cad87ffcba3b9351fb4375a8e85/pydlr/kernel.py#LL418C35-L418C35).

**Comment by jasonkaye** [comment]
Indeed, `nmax` = $\Lambda$ is not a good idea when $\Lambda$ ~ 1. A good heuristic requires experiments on a converged choice of `nmax` for the full range of possible $\Lambda$ (for large $\Lambda$, my past experiments suggest `nmax` ~ $\Lambda$ is sufficient).

**Comment by HugoStrand** [comment]
Dear Harrison and Jason,

Thank you for reporting the issue. I have added a check that uses $N_{max} = r$ in the case that $\Lambda < r$  where $r$ is the DLR rank, see e1c3ce9. This should catch the small $\Lambda$ cases gracefully.

Cheers, Hugo
