### ISSUE TITLE
Order of inputs 

### ISSUE THREAD

**Issue by andrewkhardy** [jasonkaye/libdlr#6]
I realize this may cause a lot of changes, but 

`eval_dlr_tau(G_xaa, tau_k, beta)`

should have the same order of inputs as 

`lstsq_dlr_from_tau(tau_i, G_iaa, beta)`

I see no reason why they should be flipped and it's very confusing.

**Comment by jasonkaye** [comment]
Hugo should make the final call on this, as he has a better view of what effect this change would have.

However, let me point out that `tau_k` and `tau_i` play a different role in those functions. In the first, `tau_k` is a collection of evaluation points: we are taking a DLR expansion defined by its coefficients `G_xaa` and evaluating it at a collection of points `tau_k`. In the second, `tau_i` is part of the data: we are doing a fit to data [`tau_i`,`G_iaa`] to obtain the coefficients of a DLR expansion. So I would personally have a slight, but not strong, preference for the current order: `tau_k` second in the evaluation function (coefficients -> evaluation at point) and `tau_i` first in the fitting function (data -> coefficients).

**Comment by HugoStrand** [comment]
Dear Andrew and Jason,

@andrewkhardy Thank you for the feedback on `pydlr`! I am afraid that I am siding with @jasonkaye on this question, but for the more mundane reason of not wanting to break the API. I have added a few asserts to catch the flipped arguments case, see bad03ba.

Cheers, Hugo
