### ISSUE TITLE
First Python example errors 

### ISSUE THREAD

**Issue by nicolasloizeau** [jasonkaye/libdlr#7]
After installing the current Python version with pip, the first Python example from the docs (https://libdlr.readthedocs.io/en/v1.0.0/python_examples.html) errors :
`AttributeError: 'dlr' object has no attribute 'get_dlr_frequencies'
`

**Comment by jasonkaye** [comment]
Thanks very much for pointing this out. Indeed, it seems that the pip-installed version of pydlr is somehow out of date, and for some reason does not include the method you are referencing. Could you please look into and fix this @HugoStrand ?

In the meantime, perhaps you could try installing pydlr via the developer installation instructions described [here](https://libdlr.readthedocs.io/en/v1.0.0/install.html#developer-installation), which should be relatively straightforward? Does this fix the problem?

**Comment by jasonkaye** [comment]
The pip package has been updated and the issue should be resolved in the new version.
